### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by sburina** [nickurt/laravel-rrpproxy#1]
Hi!
It's a pity there's no IDE code completion, since you took the effort to list all possible methods grouped in separate classes. Magic calls can't be resolved by laravel-ide-helper, so nothing shows in the IDE.

Here's a suggestion - in RrpProxy.php you could add a line for each group, like the following:

```php
public function keydns() { return new Api\KeyDns($this->client); }
```

Et voila, after generating the IDE helper file all the methods in this group are available in a dropdown menu!

**Comment by nickurt** [comment]
Hi @sburina,

Thanks for your suggestion, I will fix this tomorrow, but if you have already a fixed-version, feel free to create a pull-request 👍

**Comment by nickurt** [comment]
@sburina,

Digged into this today, I moved the functions to static facade-methods, seems all is still working.

Can you confirm it still works for you?

**Comment by sburina** [comment]
All ok, confirmed! :)
